# Generated by Django 4.0.1 on 2022-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('street_address', models.CharField(max_length=35)),
                ('town', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('postal', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=1)),
                ('how_heard_about', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('street_address', models.CharField(max_length=35)),
                ('town', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('postal', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=255)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=16)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('trained', models.DateField(verbose_name='trained on')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('street_address', models.CharField(max_length=35)),
                ('town', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('postal', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=1)),
                ('last_seen', models.DateField(verbose_name='last seen')),
                ('relationship', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
