# Generated by Django 4.0.1 on 2022-01-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('special_instructions', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(verbose_name='pet last seen')),
                ('picture', models.BinaryField()),
                ('temperament', models.CharField(max_length=1)),
                ('clip', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_name', models.CharField(max_length=100)),
                ('date_administered', models.DateField(verbose_name='date pet was administered vaccine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='reference',
            field=models.ManyToManyField(through='common.ClientReference', to='common.Reference'),
        ),
        migrations.CreateModel(
            name='VaccineReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.reference')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='vaccine',
            name='administered_by',
            field=models.ManyToManyField(through='common.VaccineReference', to='common.Reference'),
        ),
        migrations.CreateModel(
            name='SchedulePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.pet')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ManyToManyField(through='common.ScheduleEmployee', to='common.Employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pet',
            field=models.ManyToManyField(through='common.SchedulePet', to='common.Pet'),
        ),
        migrations.CreateModel(
            name='PetVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.pet')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='PetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.form')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccine',
            field=models.ManyToManyField(through='common.PetVaccine', to='common.Vaccine'),
        ),
        migrations.AddField(
            model_name='form',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.client'),
        ),
        migrations.AddField(
            model_name='form',
            name='pet',
            field=models.ManyToManyField(through='common.PetForm', to='common.Pet'),
        ),
        migrations.AddField(
            model_name='clientreference',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.client'),
        ),
        migrations.AddField(
            model_name='clientreference',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.reference'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateTimeField(verbose_name='date and time client requested')),
                ('status', models.CharField(max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
