# Generated by Django 4.0.1 on 2022-01-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0002_clientreference_form_pet_schedule_vaccine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreference',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientreference',
            name='reference',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='form',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.ManyToManyField(through='common.ScheduleEmployee', to='accounts.Employee'),
        ),
        migrations.AlterField(
            model_name='scheduleemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='administered_by',
            field=models.ManyToManyField(through='common.VaccineReference', to='accounts.Reference'),
        ),
        migrations.AlterField(
            model_name='vaccinereference',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reference'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientReference',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
