# Generated by Django 4.0.1 on 2022-01-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallableUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericUser',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.callableuser')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.callableuser',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.callableuser')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(max_length=1)),
                ('how_heard_about', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.callableuser',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.callableuser')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=16)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('trained', models.DateField(verbose_name='trained on')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.callableuser',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.callableuser')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.callableuser',),
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.callableuser')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.callableuser',),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.callableuser')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=1)),
                ('last_seen', models.DateField(verbose_name='last seen')),
                ('relationship', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.callableuser',),
        ),
        migrations.CreateModel(
            name='ClientReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.reference')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='reference',
            field=models.ManyToManyField(through='accounts.ClientReference', to='accounts.Reference'),
        ),
    ]
